name: Build and Test Conda Package
on:
  push:
    branches:
      - main
jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: '3.11'
    - name: Add conda to system path
      run: |
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Set up Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: test-env
        python-version: '3.11'
        auto-activate-base: true
    - name: Install Mamba
      shell: bash -l {0}
      run: |
        conda install mamba -c conda-forge
        mamba init
        source /home/runner/.bashrc
    - name: Build package 
      shell: bash -l {0}
      run: |
        mamba create --name test-env python=3.11 -y
        mamba activate test-env
        conda mambabuild .
        conda install --use-local virusnet -y
    - name: Test package 
      shell: bash -l {0}
      run: |
        virusnet --help
  
  
