name: Build and Test Conda Package
on:
  push:
    branches:
      - main
jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: test-env
          python-version: '3.11'
          channels: conda-forge
      - name: Install Mamba and conda-build
        shell: bash -l {0}
        run: |
          conda install mamba conda-build -c conda-forge
      - name: Build package
        shell: bash -l {0}
        run: |
          conda build .
          conda install --use-local virusnet -y
      - name: Test package
        shell: bash -l {0}
        run: |
          virusnet --help