name: Build and Test Conda Package
on:
  push:
    branches:
      - main
jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: test-env
          python-version: '3.11'
          channels: conda-forge
      - name: Install Mamba and Boa
        shell: bash -l {0}
        run: |
          conda install mamba boa -c conda-forge
      - name: Install Anaconda Client
        shell: bash -l {0}
        run: |
          conda install anaconda-client
      - name: Build package with boa
        shell: bash -l {0}
        run: |
          boa build .
      - name: Upload package to Anaconda
        shell: bash -l {0}
        env:
          ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_API_TOKEN }}
        run: |
          anaconda login --username GenomeNet --password "$ANACONDA_API_TOKEN"
    
